### ISSUE TITLE
“Using Dumpling” Guide

### ISSUE THREAD

**Issue by Gygaa** [emiyl/cemu.cfw.guide#32]
While using the Using Dumpling guide, I came across a problem where the web app would consistently crash unless I launched it with the SD card inserted. This was in contrast with the guide specifically saying to have the SD card inserted. When I launched it with the SD card removed, it launched correctly and I was able to then insert my SD card, refresh the detected drives, and dump my account data.

Also, I was told that the homebrew app version of Dumpling would have also fixed this problem. Perhaps both of these solutions would be worth noting in the guide.

**Comment by emiyl** [comment]
This sounds like an issue with your SD card or the dumpling app, rather than the guide. On my console it works perfectly fine with an SD card inserted. If the issue still persists with a freshly FAT32 formatted SD card, I'd recommend reporting it [here](https://github.com/dumpling-app/dumpling/issues).
